### ISSUE TITLE
vue-fragment parked

### ISSUE THREAD

**Issue by scriptcoded** [y-nk/vue-fragments#9]
Hey!
Parking package names is not allowed according to the NPM guidelines, so you could write to NPM, get the name and depricate vue-packages.

**Comment by adi518** [comment]
I feel weird for not knowing that earlier. I looked at it again and it seems to be unparked and moved in with @y-nk. Hard to tell from npm's odd presentation.

**Comment by y-nk** [comment]
@scriptcoded i actually solved this by mail with the npm community and developer involved. He assured he was working on an implementation and felt unfair that i requested the package name ; from his response, i felt like he was bitter so i offered for him to join this repo and contribute as core contributor along with his proposition.

as for now, i didn't receive any email to move forward.

I postponed maintenance of this repo too far already, and i'm sorry for that. I'll do what i can to add all the comments and feedbacks i received asap.
